"""empty message

Revision ID: 318d4f39bc76
Revises: 
Create Date: 2021-11-07 19:56:55.605016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318d4f39bc76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id_major', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_major')
    )
    op.create_table('subject',
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('name_subject', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_subject')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=25), nullable=False),
    sa.Column('email', sa.VARCHAR(length=25), nullable=False),
    sa.Column('password', sa.VARCHAR(length=205), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('student',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('name_student', sa.VARCHAR(length=45), nullable=False),
    sa.Column('last_name_student', sa.VARCHAR(length=45), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rating', sa.VARCHAR(length=45), nullable=True),
    sa.Column('id_major', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_major'], ['major.id_major'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.create_table('mark',
    sa.Column('id_mark', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['student.id_student'], ),
    sa.ForeignKeyConstraint(['id_subject'], ['subject.id_subject'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_mark')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark')
    op.drop_table('student')
    op.drop_table('user')
    op.drop_table('subject')
    op.drop_table('major')
    # ### end Alembic commands ###
