"""migration

Revision ID: c98dcfaef734
Revises: 
Create Date: 2021-10-17 11:20:39.392300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c98dcfaef734'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark')
    op.drop_table('student')
    op.drop_table('user')
    op.drop_table('subject')
    op.drop_table('major')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('major',
    sa.Column('id_major', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_major'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('subject',
    sa.Column('id_subject', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_subject'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id_student', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_student', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('last_name_student', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('rating', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('id_major', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_major'], ['major.id_major'], name='student_ibfk_1'),
    sa.PrimaryKeyConstraint('id_student'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mark',
    sa.Column('grade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_subject', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_student', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['student.id_student'], name='mark_ibfk_2'),
    sa.ForeignKeyConstraint(['id_subject'], ['subject.id_subject'], name='mark_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
